apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          ports:
            - containerPort: 5432
              name: postgres-port
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_ADMIN
            value: postgres
          - name: POSTGRES_PW
            value: "123"
          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
